---
- name: Deploy PHP Application
  hosts: client
  become: yes
  
  tasks:
    - name: Copy PHP files to the web server
      copy:
        src: /root/ansible/php/templates/virtualhost.conf.j2
        dest: /var/www/html/
        
    - name: Ensure the web server is running
      service:
        name: apache2  # Replace with your web server's service name (e.g., nginx, httpd)
        state: started
        
    - name: Execute index.php
      shell: php /var/www/html/index.php

